import os
from dotenv import load_dotenv

load_dotenv()

#twitter api
TWITTER_AUTH_CONSUMER_KEY = os.getenv("TWITTER_AUTH_CONSUMER_KEY")
TWITTER_AUTH_CONSUMER_SECRET = os.getenv("TWITTER_AUTH_CONSUMER_SECRET")
TWITTER_AUTH_BEARER_TOKEN = os.getenv("TWITTER_AUTH_BEARER_TOKEN")
TWITTER_AUTH_ACCESS_TOKEN = os.getenv("TWITTER_AUTH_ACCESS_TOKEN")
TWITTER_AUTH_ACCESS_TOKEN_SECRET = os.getenv("TWITTER_AUTH_ACCESS_TOKEN_SECRET")

# openai api
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_CLIENT_ID = os.getenv("CLIENT_ID")
OPENAI_CLIENT_SECRET = os.getenv("CLIENT_SECRET")

# tavily api key
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")